package com.yang.vo;

import java.math.BigDecimal;

public class ProductVO {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String productId;

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String productName; /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.POINT_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String pointPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.SALE_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String saleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_HOT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String productHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PIC_URL
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CASH_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String cashPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODCUT_TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String prodcutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.DESCRIPTION
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String description;

    public String getPointPrice() {
        return pointPrice;
    }

    public void setPointPrice(String pointPrice) {
        this.pointPrice = pointPrice;
    }

    public String getSaleCount() {
        return saleCount;
    }

    public void setSaleCount(String saleCount) {
        this.saleCount = saleCount;
    }

    public String getProductHot() {
        return productHot;
    }

    public void setProductHot(String productHot) {
        this.productHot = productHot;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getCashPrice() {
        return cashPrice;
    }

    public void setCashPrice(String cashPrice) {
        this.cashPrice = cashPrice;
    }

    public String getProdcutType() {
        return prodcutType;
    }

    public void setProdcutType(String prodcutType) {
        this.prodcutType = prodcutType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
