package com.yang.dao;

import com.yang.domain.Admin;
import com.yang.domain.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int deleteByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    Admin selectByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByPrimaryKey(Admin record);
}