package com.yang.dao;

import com.yang.domain.AwardRecord;
import com.yang.domain.AwardRecordExample;
import java.util.List;

import com.yang.domain.RecommendHis;
import org.apache.ibatis.annotations.Param;

public interface AwardRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int countByExample(AwardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int deleteByExample(AwardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int deleteByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int insert(AwardRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int insertSelective(AwardRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    List<AwardRecord> selectByExample(AwardRecordExample example);

    List<RecommendHis> selectRcmdHis();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    AwardRecord selectByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") AwardRecord record, @Param("example") AwardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByExample(@Param("record") AwardRecord record, @Param("example") AwardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByPrimaryKeySelective(AwardRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByPrimaryKey(AwardRecord record);
}