package com.yang.dao;

import com.yang.domain.Cart;
import com.yang.domain.CartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int updateByExample(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    int updateByPrimaryKey(Cart record);
}