package com.yang.dao;

import com.yang.domain.PocketRecord;
import com.yang.domain.PocketRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PocketRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int countByExample(PocketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int deleteByExample(PocketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int insert(PocketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int insertSelective(PocketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    List<PocketRecord> selectByExample(PocketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    PocketRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") PocketRecord record, @Param("example") PocketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByExample(@Param("record") PocketRecord record, @Param("example") PocketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByPrimaryKeySelective(PocketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POCKET_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByPrimaryKey(PocketRecord record);
}