package com.yang.dao;

import com.yang.domain.ShoppingRecord;
import com.yang.domain.ShoppingRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShoppingRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int countByExample(ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int deleteByExample(ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int deleteByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int insert(ShoppingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int insertSelective(ShoppingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    List<ShoppingRecord> selectByExample(ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    ShoppingRecord selectByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShoppingRecord record, @Param("example") ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByExample(@Param("record") ShoppingRecord record, @Param("example") ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByPrimaryKeySelective(ShoppingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOPPING_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    int updateByPrimaryKey(ShoppingRecord record);
}