package com.yang.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AwardRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public AwardRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOIdIsNull() {
            addCriterion("O_ID is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("O_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(Integer value) {
            addCriterion("O_ID =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(Integer value) {
            addCriterion("O_ID <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(Integer value) {
            addCriterion("O_ID >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("O_ID >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(Integer value) {
            addCriterion("O_ID <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(Integer value) {
            addCriterion("O_ID <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<Integer> values) {
            addCriterion("O_ID in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<Integer> values) {
            addCriterion("O_ID not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(Integer value1, Integer value2) {
            addCriterion("O_ID between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(Integer value1, Integer value2) {
            addCriterion("O_ID not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andVidIsNull() {
            addCriterion("VID is null");
            return (Criteria) this;
        }

        public Criteria andVidIsNotNull() {
            addCriterion("VID is not null");
            return (Criteria) this;
        }

        public Criteria andVidEqualTo(String value) {
            addCriterion("VID =", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotEqualTo(String value) {
            addCriterion("VID <>", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThan(String value) {
            addCriterion("VID >", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThanOrEqualTo(String value) {
            addCriterion("VID >=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThan(String value) {
            addCriterion("VID <", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThanOrEqualTo(String value) {
            addCriterion("VID <=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLike(String value) {
            addCriterion("VID like", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotLike(String value) {
            addCriterion("VID not like", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidIn(List<String> values) {
            addCriterion("VID in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotIn(List<String> values) {
            addCriterion("VID not in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidBetween(String value1, String value2) {
            addCriterion("VID between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotBetween(String value1, String value2) {
            addCriterion("VID not between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andAwardTypeIsNull() {
            addCriterion("AWARD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAwardTypeIsNotNull() {
            addCriterion("AWARD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAwardTypeEqualTo(String value) {
            addCriterion("AWARD_TYPE =", value, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeNotEqualTo(String value) {
            addCriterion("AWARD_TYPE <>", value, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeGreaterThan(String value) {
            addCriterion("AWARD_TYPE >", value, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("AWARD_TYPE >=", value, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeLessThan(String value) {
            addCriterion("AWARD_TYPE <", value, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeLessThanOrEqualTo(String value) {
            addCriterion("AWARD_TYPE <=", value, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeLike(String value) {
            addCriterion("AWARD_TYPE like", value, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeNotLike(String value) {
            addCriterion("AWARD_TYPE not like", value, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeIn(List<String> values) {
            addCriterion("AWARD_TYPE in", values, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeNotIn(List<String> values) {
            addCriterion("AWARD_TYPE not in", values, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeBetween(String value1, String value2) {
            addCriterion("AWARD_TYPE between", value1, value2, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardTypeNotBetween(String value1, String value2) {
            addCriterion("AWARD_TYPE not between", value1, value2, "awardType");
            return (Criteria) this;
        }

        public Criteria andAwardAmountIsNull() {
            addCriterion("AWARD_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAwardAmountIsNotNull() {
            addCriterion("AWARD_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAwardAmountEqualTo(String value) {
            addCriterion("AWARD_AMOUNT =", value, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountNotEqualTo(String value) {
            addCriterion("AWARD_AMOUNT <>", value, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountGreaterThan(String value) {
            addCriterion("AWARD_AMOUNT >", value, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountGreaterThanOrEqualTo(String value) {
            addCriterion("AWARD_AMOUNT >=", value, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountLessThan(String value) {
            addCriterion("AWARD_AMOUNT <", value, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountLessThanOrEqualTo(String value) {
            addCriterion("AWARD_AMOUNT <=", value, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountLike(String value) {
            addCriterion("AWARD_AMOUNT like", value, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountNotLike(String value) {
            addCriterion("AWARD_AMOUNT not like", value, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountIn(List<String> values) {
            addCriterion("AWARD_AMOUNT in", values, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountNotIn(List<String> values) {
            addCriterion("AWARD_AMOUNT not in", values, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountBetween(String value1, String value2) {
            addCriterion("AWARD_AMOUNT between", value1, value2, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andAwardAmountNotBetween(String value1, String value2) {
            addCriterion("AWARD_AMOUNT not between", value1, value2, "awardAmount");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNull() {
            addCriterion("SERVICE_FEE is null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNotNull() {
            addCriterion("SERVICE_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeEqualTo(BigDecimal value) {
            addCriterion("SERVICE_FEE =", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotEqualTo(BigDecimal value) {
            addCriterion("SERVICE_FEE <>", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThan(BigDecimal value) {
            addCriterion("SERVICE_FEE >", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SERVICE_FEE >=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThan(BigDecimal value) {
            addCriterion("SERVICE_FEE <", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SERVICE_FEE <=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIn(List<BigDecimal> values) {
            addCriterion("SERVICE_FEE in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotIn(List<BigDecimal> values) {
            addCriterion("SERVICE_FEE not in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SERVICE_FEE between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SERVICE_FEE not between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andRelatedVipIsNull() {
            addCriterion("RELATED_VIP is null");
            return (Criteria) this;
        }

        public Criteria andRelatedVipIsNotNull() {
            addCriterion("RELATED_VIP is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedVipEqualTo(String value) {
            addCriterion("RELATED_VIP =", value, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipNotEqualTo(String value) {
            addCriterion("RELATED_VIP <>", value, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipGreaterThan(String value) {
            addCriterion("RELATED_VIP >", value, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipGreaterThanOrEqualTo(String value) {
            addCriterion("RELATED_VIP >=", value, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipLessThan(String value) {
            addCriterion("RELATED_VIP <", value, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipLessThanOrEqualTo(String value) {
            addCriterion("RELATED_VIP <=", value, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipLike(String value) {
            addCriterion("RELATED_VIP like", value, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipNotLike(String value) {
            addCriterion("RELATED_VIP not like", value, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipIn(List<String> values) {
            addCriterion("RELATED_VIP in", values, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipNotIn(List<String> values) {
            addCriterion("RELATED_VIP not in", values, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipBetween(String value1, String value2) {
            addCriterion("RELATED_VIP between", value1, value2, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andRelatedVipNotBetween(String value1, String value2) {
            addCriterion("RELATED_VIP not between", value1, value2, "relatedVip");
            return (Criteria) this;
        }

        public Criteria andAwardTimeIsNull() {
            addCriterion("AWARD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAwardTimeIsNotNull() {
            addCriterion("AWARD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAwardTimeEqualTo(Date value) {
            addCriterion("AWARD_TIME =", value, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeNotEqualTo(Date value) {
            addCriterion("AWARD_TIME <>", value, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeGreaterThan(Date value) {
            addCriterion("AWARD_TIME >", value, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("AWARD_TIME >=", value, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeLessThan(Date value) {
            addCriterion("AWARD_TIME <", value, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeLessThanOrEqualTo(Date value) {
            addCriterion("AWARD_TIME <=", value, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeIn(List<Date> values) {
            addCriterion("AWARD_TIME in", values, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeNotIn(List<Date> values) {
            addCriterion("AWARD_TIME not in", values, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeBetween(Date value1, Date value2) {
            addCriterion("AWARD_TIME between", value1, value2, "awardTime");
            return (Criteria) this;
        }

        public Criteria andAwardTimeNotBetween(Date value1, Date value2) {
            addCriterion("AWARD_TIME not between", value1, value2, "awardTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 01 08:54:57 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AWARD_RECORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}