package com.yang.domain;

public class Cart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer productCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.O_ID
     *
     * @return the value of CART.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.POINT_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Float pointPrice;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PIC_URL
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CASH_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Float cashPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODCUT_TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String prodcutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.DESCRIPTION
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_ID
     *
     * @return the value of PRODUCT.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */

    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.O_ID
     *
     * @param oId the value for CART.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.VIP_ID
     *
     * @return the value of CART.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.VIP_ID
     *
     * @param vipId the value for CART.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setVipId(String vipId) {
        this.vipId = vipId == null ? null : vipId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.PRODUCT_ID
     *
     * @return the value of CART.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.PRODUCT_ID
     *
     * @param productId the value for CART.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.PRODUCT_COUNT
     *
     * @return the value of CART.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.PRODUCT_COUNT
     *
     * @param productCount the value for CART.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Float getPointPrice() {
        return pointPrice;
    }

    public void setPointPrice(Float pointPrice) {
        this.pointPrice = pointPrice;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public Float getCashPrice() {
        return cashPrice;
    }

    public void setCashPrice(Float cashPrice) {
        this.cashPrice = cashPrice;
    }

    public String getProdcutType() {
        return prodcutType;
    }

    public void setProdcutType(String prodcutType) {
        this.prodcutType = prodcutType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}