package com.yang.domain;

public class Cart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.VIP_ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    private String vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.PRODUCT_ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.COUNT
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.ID
     *
     * @return the value of CART.ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.ID
     *
     * @param id the value for CART.ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.VIP_ID
     *
     * @return the value of CART.VIP_ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    public String getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.VIP_ID
     *
     * @param vipId the value for CART.VIP_ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    public void setVipId(String vipId) {
        this.vipId = vipId == null ? null : vipId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.PRODUCT_ID
     *
     * @return the value of CART.PRODUCT_ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.PRODUCT_ID
     *
     * @param productId the value for CART.PRODUCT_ID
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.COUNT
     *
     * @return the value of CART.COUNT
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.COUNT
     *
     * @param count the value for CART.COUNT
     *
     * @mbggenerated Wed Oct 31 15:16:50 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}