package com.yang.domain;

public class Cart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CART.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer productCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.O_ID
     *
     * @return the value of CART.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.O_ID
     *
     * @param oId the value for CART.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.VIP_ID
     *
     * @return the value of CART.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.VIP_ID
     *
     * @param vipId the value for CART.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setVipId(String vipId) {
        this.vipId = vipId == null ? null : vipId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.PRODUCT_ID
     *
     * @return the value of CART.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.PRODUCT_ID
     *
     * @param productId the value for CART.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CART.PRODUCT_COUNT
     *
     * @return the value of CART.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CART.PRODUCT_COUNT
     *
     * @param productCount the value for CART.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }
}