package com.yang.domain;


import com.sun.xml.internal.bind.v2.runtime.reflect.opt.Const;
import com.yang.util.Constant;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class PocketRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POCKET_RECORD.ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POCKET_RECORD.TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Date time;
    private String stringTime;

    public String getStringTime() {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
        return sdf.format(time);
    }

    public void setStringTime(String stringTime) {
        this.stringTime = stringTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POCKET_RECORD.TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String type;
    /**
     * 资金状态
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POCKET_RECORD.AMOUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POCKET_RECORD.RELATED_VIPID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String relatedVipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POCKET_RECORD.POINT_OR_CASH
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String pointOrCash;
    /**
     * 购买方式
     */
    private String pointOrCashName;
    private static  Map<String,String> numberToName=new HashMap<>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POCKET_RECORD.ID
     *
     * @return the value of POCKET_RECORD.ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POCKET_RECORD.ID
     *
     * @param id the value for POCKET_RECORD.ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POCKET_RECORD.TIME
     *
     * @return the value of POCKET_RECORD.TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POCKET_RECORD.TIME
     *
     * @param time the value for POCKET_RECORD.TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POCKET_RECORD.TYPE
     *
     * @return the value of POCKET_RECORD.TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POCKET_RECORD.TYPE
     *
     * @param type the value for POCKET_RECORD.TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POCKET_RECORD.AMOUNT
     *
     * @return the value of POCKET_RECORD.AMOUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POCKET_RECORD.AMOUNT
     *
     * @param amount the value for POCKET_RECORD.AMOUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POCKET_RECORD.RELATED_VIPID
     *
     * @return the value of POCKET_RECORD.RELATED_VIPID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getRelatedVipid() {
        return relatedVipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POCKET_RECORD.RELATED_VIPID
     *
     * @param relatedVipid the value for POCKET_RECORD.RELATED_VIPID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setRelatedVipid(String relatedVipid) {
        this.relatedVipid = relatedVipid == null ? null : relatedVipid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POCKET_RECORD.POINT_OR_CASH
     *
     * @return the value of POCKET_RECORD.POINT_OR_CASH
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getPointOrCash() {
        return pointOrCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POCKET_RECORD.POINT_OR_CASH
     *
     * @param pointOrCash the value for POCKET_RECORD.POINT_OR_CASH
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setPointOrCash(String pointOrCash) {
        this.pointOrCash = pointOrCash == null ? null : pointOrCash.trim();
    }

    public String getTypeName() {
        return numberToName.get(getType());
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getPointOrCashName() {
        return numberToName.get(getPointOrCash());
    }

    public void setPointOrCashName(String pointOrCashName) {
        this.pointOrCashName = pointOrCashName;
    }

    public Map<String, String> getNumberToName() {
        return numberToName;
    }

    public void setNumberToName(Map<String, String> numberToName) {
        this.numberToName = numberToName;
    }

    static {
        numberToName.put(Constant.POCKET_REFUND,Constant.POCKET_REFUND_NAME);
        numberToName.put(Constant.POCKET_SHOPPING,Constant.POCKET_SHOPPING_NAME);
        numberToName.put(Constant.SHOPPING_BY_CASH,Constant.SHOPPING_BY_CASH_NAME);
        numberToName.put(Constant.SHOPPING_BY_POINT,Constant.SHOPPING_BY_POINT_NAME);
        numberToName.put(Constant.POCKET_RECHARGE,Constant.POCKET_RECHARGE_NAME);
    }
}