package com.yang.domain;

import java.math.BigDecimal;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.POINT_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private BigDecimal pointPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.SALE_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer saleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_HOT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer productHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PIC_URL
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CASH_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Float cashPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODCUT_TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String prodcutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.DESCRIPTION
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_ID
     *
     * @return the value of PRODUCT.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_ID
     *
     * @param productId the value for PRODUCT.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_NAME
     *
     * @return the value of PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_NAME
     *
     * @param productName the value for PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.POINT_PRICE
     *
     * @return the value of PRODUCT.POINT_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public BigDecimal getPointPrice() {
        return pointPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.POINT_PRICE
     *
     * @param pointPrice the value for PRODUCT.POINT_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setPointPrice(BigDecimal pointPrice) {
        this.pointPrice = pointPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.SALE_COUNT
     *
     * @return the value of PRODUCT.SALE_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getSaleCount() {
        return saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.SALE_COUNT
     *
     * @param saleCount the value for PRODUCT.SALE_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_HOT
     *
     * @return the value of PRODUCT.PRODUCT_HOT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getProductHot() {
        return productHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_HOT
     *
     * @param productHot the value for PRODUCT.PRODUCT_HOT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductHot(Integer productHot) {
        this.productHot = productHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PIC_URL
     *
     * @return the value of PRODUCT.PIC_URL
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PIC_URL
     *
     * @param picUrl the value for PRODUCT.PIC_URL
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CASH_PRICE
     *
     * @return the value of PRODUCT.CASH_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Float getCashPrice() {
        return cashPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CASH_PRICE
     *
     * @param cashPrice the value for PRODUCT.CASH_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setCashPrice(Float cashPrice) {
        this.cashPrice = cashPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODCUT_TYPE
     *
     * @return the value of PRODUCT.PRODCUT_TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getProdcutType() {
        return prodcutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODCUT_TYPE
     *
     * @param prodcutType the value for PRODUCT.PRODCUT_TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProdcutType(String prodcutType) {
        this.prodcutType = prodcutType == null ? null : prodcutType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.DESCRIPTION
     *
     * @return the value of PRODUCT.DESCRIPTION
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.DESCRIPTION
     *
     * @param description the value for PRODUCT.DESCRIPTION
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}