package com.yang.domain;


import java.util.Date;

public class ShoppingRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOPPING_RECORD.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOPPING_RECORD.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOPPING_RECORD.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOPPING_RECORD.ADD_TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Date addTime;

    private String stringAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOPPING_RECORD.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer productCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOPPING_RECORD.PRODUCT_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Float productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOPPING_RECORD.TOTAL_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Float totalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOPPING_RECORD.O_ID
     *
     * @return the value of SHOPPING_RECORD.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PIC_URL
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String picUrl;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODCUT_TYPE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String prodcutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.DESCRIPTION
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String description;

    public String getProdcutType() {
        return prodcutType;
    }

    public void setProdcutType(String prodcutType) {
        this.prodcutType = prodcutType;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOPPING_RECORD.O_ID
     *
     * @param oId the value for SHOPPING_RECORD.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOPPING_RECORD.VIP_ID
     *
     * @return the value of SHOPPING_RECORD.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOPPING_RECORD.VIP_ID
     *
     * @param vipId the value for SHOPPING_RECORD.VIP_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setVipId(String vipId) {
        this.vipId = vipId == null ? null : vipId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOPPING_RECORD.PRODUCT_ID
     *
     * @return the value of SHOPPING_RECORD.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOPPING_RECORD.PRODUCT_ID
     *
     * @param productId the value for SHOPPING_RECORD.PRODUCT_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOPPING_RECORD.ADD_TIME
     *
     * @return the value of SHOPPING_RECORD.ADD_TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOPPING_RECORD.ADD_TIME
     *
     * @param addTime the value for SHOPPING_RECORD.ADD_TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOPPING_RECORD.PRODUCT_COUNT
     *
     * @return the value of SHOPPING_RECORD.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOPPING_RECORD.PRODUCT_COUNT
     *
     * @param productCount the value for SHOPPING_RECORD.PRODUCT_COUNT
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOPPING_RECORD.PRODUCT_PRICE
     *
     * @return the value of SHOPPING_RECORD.PRODUCT_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Float getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOPPING_RECORD.PRODUCT_PRICE
     *
     * @param productPrice the value for SHOPPING_RECORD.PRODUCT_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setProductPrice(Float productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOPPING_RECORD.TOTAL_PRICE
     *
     * @return the value of SHOPPING_RECORD.TOTAL_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Float getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOPPING_RECORD.TOTAL_PRICE
     *
     * @param totalPrice the value for SHOPPING_RECORD.TOTAL_PRICE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    public String getStringAddTime() {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
        return sdf.format(addTime);
    }

    public void setStringAddTime(String stringAddTime) {
        this.stringAddTime = stringAddTime;
    }
}