package com.yang.domain;

public class VidGenerator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VID_GENERATOR.O_ID
     *
     * @mbggenerated Thu Nov 08 21:27:07 CST 2018
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VID_GENERATOR.SUFFIX_NUMBER
     *
     * @mbggenerated Thu Nov 08 21:27:07 CST 2018
     */
    private Integer suffixNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VID_GENERATOR.O_ID
     *
     * @return the value of VID_GENERATOR.O_ID
     *
     * @mbggenerated Thu Nov 08 21:27:07 CST 2018
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VID_GENERATOR.O_ID
     *
     * @param oId the value for VID_GENERATOR.O_ID
     *
     * @mbggenerated Thu Nov 08 21:27:07 CST 2018
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VID_GENERATOR.SUFFIX_NUMBER
     *
     * @return the value of VID_GENERATOR.SUFFIX_NUMBER
     *
     * @mbggenerated Thu Nov 08 21:27:07 CST 2018
     */
    public Integer getSuffixNumber() {
        return suffixNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VID_GENERATOR.SUFFIX_NUMBER
     *
     * @param suffixNumber the value for VID_GENERATOR.SUFFIX_NUMBER
     *
     * @mbggenerated Thu Nov 08 21:27:07 CST 2018
     */
    public void setSuffixNumber(Integer suffixNumber) {
        this.suffixNumber = suffixNumber;
    }

    @Override
    public String toString() {
        return "VidGenerator{" +
                "oId=" + oId +
                ", suffixNumber=" + suffixNumber +
                '}';
    }
}