package com.yang.domain;


import java.util.Date;

public class Vip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.VID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.V_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String vName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.PHONE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.V_CLASS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String vClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.REGISTE_TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Date registeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.RECOMMEND_PERSON
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String recommendPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.RECOMMEND_VID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String recommendVid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.BANK_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.BANK_NUMBER
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String bankNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.ADDRESS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.BANLANCE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Float banlance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.POINTS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private Float points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.V_PASSWORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String vPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIP.PAY_PASSWORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    private String payPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.O_ID
     *
     * @return the value of VIP.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.O_ID
     *
     * @param oId the value for VIP.O_ID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.VID
     *
     * @return the value of VIP.VID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.VID
     *
     * @param vid the value for VIP.VID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.V_NAME
     *
     * @return the value of VIP.V_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.V_NAME
     *
     * @param vName the value for VIP.V_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    @Override
    public String toString() {
        return "Vip{" +
                "oId=" + oId +
                ", vid='" + vid + '\'' +
                ", vName='" + vName + '\'' +
                ", phone='" + phone + '\'' +
                ", vClass='" + vClass + '\'' +
                ", registeTime=" + registeTime +
                ", recommendPerson='" + recommendPerson + '\'' +
                ", recommendVid=" + recommendVid +
                ", bankName='" + bankName + '\'' +
                ", bankNumber='" + bankNumber + '\'' +
                ", address='" + address + '\'' +
                ", banlance=" + banlance +
                ", points=" + points +
                ", vPassword='" + vPassword + '\'' +
                ", payPassword='" + payPassword + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.PHONE
     *
     * @return the value of VIP.PHONE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.PHONE
     *
     * @param phone the value for VIP.PHONE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.V_CLASS
     *
     * @return the value of VIP.V_CLASS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getvClass() {
        return vClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.V_CLASS
     *
     * @param vClass the value for VIP.V_CLASS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setvClass(String vClass) {
        this.vClass = vClass == null ? null : vClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.REGISTE_TIME
     *
     * @return the value of VIP.REGISTE_TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Date getRegisteTime() {
        return registeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.REGISTE_TIME
     *
     * @param registeTime the value for VIP.REGISTE_TIME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setRegisteTime(Date registeTime) {
        this.registeTime = registeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.RECOMMEND_PERSON
     *
     * @return the value of VIP.RECOMMEND_PERSON
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getRecommendPerson() {
        return recommendPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.RECOMMEND_PERSON
     *
     * @param recommendPerson the value for VIP.RECOMMEND_PERSON
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setRecommendPerson(String recommendPerson) {
        this.recommendPerson = recommendPerson == null ? null : recommendPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.RECOMMEND_VID
     *
     * @return the value of VIP.RECOMMEND_VID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getRecommendVid() {
        return recommendVid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.RECOMMEND_VID
     *
     * @param recommendVid the value for VIP.RECOMMEND_VID
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setRecommendVid(String recommendVid) {
        this.recommendVid = recommendVid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.BANK_NAME
     *
     * @return the value of VIP.BANK_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.BANK_NAME
     *
     * @param bankName the value for VIP.BANK_NAME
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.BANK_NUMBER
     *
     * @return the value of VIP.BANK_NUMBER
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.BANK_NUMBER
     *
     * @param bankNumber the value for VIP.BANK_NUMBER
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber == null ? null : bankNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.ADDRESS
     *
     * @return the value of VIP.ADDRESS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.ADDRESS
     *
     * @param address the value for VIP.ADDRESS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.BANLANCE
     *
     * @return the value of VIP.BANLANCE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Float getBanlance() {
        return banlance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.BANLANCE
     *
     * @param banlance the value for VIP.BANLANCE
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setBanlance(Float banlance) {
        this.banlance = banlance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.POINTS
     *
     * @return the value of VIP.POINTS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Float getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.POINTS
     *
     * @param points the value for VIP.POINTS
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setPoints(Float points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.V_PASSWORD
     *
     * @return the value of VIP.V_PASSWORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getvPassword() {
        return vPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.V_PASSWORD
     *
     * @param vPassword the value for VIP.V_PASSWORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setvPassword(String vPassword) {
        this.vPassword = vPassword == null ? null : vPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIP.PAY_PASSWORD
     *
     * @return the value of VIP.PAY_PASSWORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIP.PAY_PASSWORD
     *
     * @param payPassword the value for VIP.PAY_PASSWORD
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }
}