package com.yang.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VipExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public VipExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOIdIsNull() {
            addCriterion("O_ID is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("O_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(Integer value) {
            addCriterion("O_ID =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(Integer value) {
            addCriterion("O_ID <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(Integer value) {
            addCriterion("O_ID >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("O_ID >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(Integer value) {
            addCriterion("O_ID <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(Integer value) {
            addCriterion("O_ID <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<Integer> values) {
            addCriterion("O_ID in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<Integer> values) {
            addCriterion("O_ID not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(Integer value1, Integer value2) {
            addCriterion("O_ID between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(Integer value1, Integer value2) {
            addCriterion("O_ID not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andVidIsNull() {
            addCriterion("VID is null");
            return (Criteria) this;
        }

        public Criteria andVidIsNotNull() {
            addCriterion("VID is not null");
            return (Criteria) this;
        }

        public Criteria andVidEqualTo(String value) {
            addCriterion("VID =", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotEqualTo(String value) {
            addCriterion("VID <>", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThan(String value) {
            addCriterion("VID >", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThanOrEqualTo(String value) {
            addCriterion("VID >=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThan(String value) {
            addCriterion("VID <", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThanOrEqualTo(String value) {
            addCriterion("VID <=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLike(String value) {
            addCriterion("VID like", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotLike(String value) {
            addCriterion("VID not like", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidIn(List<String> values) {
            addCriterion("VID in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotIn(List<String> values) {
            addCriterion("VID not in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidBetween(String value1, String value2) {
            addCriterion("VID between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotBetween(String value1, String value2) {
            addCriterion("VID not between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVNameIsNull() {
            addCriterion("V_NAME is null");
            return (Criteria) this;
        }

        public Criteria andVNameIsNotNull() {
            addCriterion("V_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andVNameEqualTo(String value) {
            addCriterion("V_NAME =", value, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameNotEqualTo(String value) {
            addCriterion("V_NAME <>", value, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameGreaterThan(String value) {
            addCriterion("V_NAME >", value, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameGreaterThanOrEqualTo(String value) {
            addCriterion("V_NAME >=", value, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameLessThan(String value) {
            addCriterion("V_NAME <", value, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameLessThanOrEqualTo(String value) {
            addCriterion("V_NAME <=", value, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameLike(String value) {
            addCriterion("V_NAME like", value, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameNotLike(String value) {
            addCriterion("V_NAME not like", value, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameIn(List<String> values) {
            addCriterion("V_NAME in", values, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameNotIn(List<String> values) {
            addCriterion("V_NAME not in", values, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameBetween(String value1, String value2) {
            addCriterion("V_NAME between", value1, value2, "vName");
            return (Criteria) this;
        }

        public Criteria andVNameNotBetween(String value1, String value2) {
            addCriterion("V_NAME not between", value1, value2, "vName");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("PHONE like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("PHONE not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andVClassIsNull() {
            addCriterion("V_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andVClassIsNotNull() {
            addCriterion("V_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andVClassEqualTo(String value) {
            addCriterion("V_CLASS =", value, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassNotEqualTo(String value) {
            addCriterion("V_CLASS <>", value, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassGreaterThan(String value) {
            addCriterion("V_CLASS >", value, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassGreaterThanOrEqualTo(String value) {
            addCriterion("V_CLASS >=", value, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassLessThan(String value) {
            addCriterion("V_CLASS <", value, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassLessThanOrEqualTo(String value) {
            addCriterion("V_CLASS <=", value, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassLike(String value) {
            addCriterion("V_CLASS like", value, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassNotLike(String value) {
            addCriterion("V_CLASS not like", value, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassIn(List<String> values) {
            addCriterion("V_CLASS in", values, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassNotIn(List<String> values) {
            addCriterion("V_CLASS not in", values, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassBetween(String value1, String value2) {
            addCriterion("V_CLASS between", value1, value2, "vClass");
            return (Criteria) this;
        }

        public Criteria andVClassNotBetween(String value1, String value2) {
            addCriterion("V_CLASS not between", value1, value2, "vClass");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeIsNull() {
            addCriterion("REGISTE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeIsNotNull() {
            addCriterion("REGISTE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeEqualTo(Date value) {
            addCriterion("REGISTE_TIME =", value, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeNotEqualTo(Date value) {
            addCriterion("REGISTE_TIME <>", value, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeGreaterThan(Date value) {
            addCriterion("REGISTE_TIME >", value, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTE_TIME >=", value, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeLessThan(Date value) {
            addCriterion("REGISTE_TIME <", value, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTE_TIME <=", value, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeIn(List<Date> values) {
            addCriterion("REGISTE_TIME in", values, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeNotIn(List<Date> values) {
            addCriterion("REGISTE_TIME not in", values, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeBetween(Date value1, Date value2) {
            addCriterion("REGISTE_TIME between", value1, value2, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRegisteTimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTE_TIME not between", value1, value2, "registeTime");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonIsNull() {
            addCriterion("RECOMMEND_PERSON is null");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonIsNotNull() {
            addCriterion("RECOMMEND_PERSON is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonEqualTo(String value) {
            addCriterion("RECOMMEND_PERSON =", value, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonNotEqualTo(String value) {
            addCriterion("RECOMMEND_PERSON <>", value, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonGreaterThan(String value) {
            addCriterion("RECOMMEND_PERSON >", value, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonGreaterThanOrEqualTo(String value) {
            addCriterion("RECOMMEND_PERSON >=", value, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonLessThan(String value) {
            addCriterion("RECOMMEND_PERSON <", value, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonLessThanOrEqualTo(String value) {
            addCriterion("RECOMMEND_PERSON <=", value, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonLike(String value) {
            addCriterion("RECOMMEND_PERSON like", value, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonNotLike(String value) {
            addCriterion("RECOMMEND_PERSON not like", value, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonIn(List<String> values) {
            addCriterion("RECOMMEND_PERSON in", values, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonNotIn(List<String> values) {
            addCriterion("RECOMMEND_PERSON not in", values, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonBetween(String value1, String value2) {
            addCriterion("RECOMMEND_PERSON between", value1, value2, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendPersonNotBetween(String value1, String value2) {
            addCriterion("RECOMMEND_PERSON not between", value1, value2, "recommendPerson");
            return (Criteria) this;
        }

        public Criteria andRecommendVidIsNull() {
            addCriterion("RECOMMEND_VID is null");
            return (Criteria) this;
        }

        public Criteria andRecommendVidIsNotNull() {
            addCriterion("RECOMMEND_VID is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendVidEqualTo(Integer value) {
            addCriterion("RECOMMEND_VID =", value, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidNotEqualTo(Integer value) {
            addCriterion("RECOMMEND_VID <>", value, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidGreaterThan(Integer value) {
            addCriterion("RECOMMEND_VID >", value, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECOMMEND_VID >=", value, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidLessThan(Integer value) {
            addCriterion("RECOMMEND_VID <", value, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidLessThanOrEqualTo(Integer value) {
            addCriterion("RECOMMEND_VID <=", value, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidIn(List<Integer> values) {
            addCriterion("RECOMMEND_VID in", values, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidNotIn(List<Integer> values) {
            addCriterion("RECOMMEND_VID not in", values, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidBetween(Integer value1, Integer value2) {
            addCriterion("RECOMMEND_VID between", value1, value2, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andRecommendVidNotBetween(Integer value1, Integer value2) {
            addCriterion("RECOMMEND_VID not between", value1, value2, "recommendVid");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNumberIsNull() {
            addCriterion("BANK_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andBankNumberIsNotNull() {
            addCriterion("BANK_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andBankNumberEqualTo(String value) {
            addCriterion("BANK_NUMBER =", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberNotEqualTo(String value) {
            addCriterion("BANK_NUMBER <>", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberGreaterThan(String value) {
            addCriterion("BANK_NUMBER >", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NUMBER >=", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberLessThan(String value) {
            addCriterion("BANK_NUMBER <", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberLessThanOrEqualTo(String value) {
            addCriterion("BANK_NUMBER <=", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberLike(String value) {
            addCriterion("BANK_NUMBER like", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberNotLike(String value) {
            addCriterion("BANK_NUMBER not like", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberIn(List<String> values) {
            addCriterion("BANK_NUMBER in", values, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberNotIn(List<String> values) {
            addCriterion("BANK_NUMBER not in", values, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberBetween(String value1, String value2) {
            addCriterion("BANK_NUMBER between", value1, value2, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberNotBetween(String value1, String value2) {
            addCriterion("BANK_NUMBER not between", value1, value2, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andBanlanceIsNull() {
            addCriterion("BANLANCE is null");
            return (Criteria) this;
        }

        public Criteria andBanlanceIsNotNull() {
            addCriterion("BANLANCE is not null");
            return (Criteria) this;
        }

        public Criteria andBanlanceEqualTo(BigDecimal value) {
            addCriterion("BANLANCE =", value, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceNotEqualTo(BigDecimal value) {
            addCriterion("BANLANCE <>", value, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceGreaterThan(BigDecimal value) {
            addCriterion("BANLANCE >", value, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BANLANCE >=", value, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceLessThan(BigDecimal value) {
            addCriterion("BANLANCE <", value, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BANLANCE <=", value, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceIn(List<BigDecimal> values) {
            addCriterion("BANLANCE in", values, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceNotIn(List<BigDecimal> values) {
            addCriterion("BANLANCE not in", values, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BANLANCE between", value1, value2, "banlance");
            return (Criteria) this;
        }

        public Criteria andBanlanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BANLANCE not between", value1, value2, "banlance");
            return (Criteria) this;
        }

        public Criteria andPointsIsNull() {
            addCriterion("POINTS is null");
            return (Criteria) this;
        }

        public Criteria andPointsIsNotNull() {
            addCriterion("POINTS is not null");
            return (Criteria) this;
        }

        public Criteria andPointsEqualTo(BigDecimal value) {
            addCriterion("POINTS =", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsNotEqualTo(BigDecimal value) {
            addCriterion("POINTS <>", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsGreaterThan(BigDecimal value) {
            addCriterion("POINTS >", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("POINTS >=", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsLessThan(BigDecimal value) {
            addCriterion("POINTS <", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("POINTS <=", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsIn(List<BigDecimal> values) {
            addCriterion("POINTS in", values, "points");
            return (Criteria) this;
        }

        public Criteria andPointsNotIn(List<BigDecimal> values) {
            addCriterion("POINTS not in", values, "points");
            return (Criteria) this;
        }

        public Criteria andPointsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POINTS between", value1, value2, "points");
            return (Criteria) this;
        }

        public Criteria andPointsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POINTS not between", value1, value2, "points");
            return (Criteria) this;
        }

        public Criteria andVPasswordIsNull() {
            addCriterion("V_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andVPasswordIsNotNull() {
            addCriterion("V_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andVPasswordEqualTo(String value) {
            addCriterion("V_PASSWORD =", value, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordNotEqualTo(String value) {
            addCriterion("V_PASSWORD <>", value, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordGreaterThan(String value) {
            addCriterion("V_PASSWORD >", value, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("V_PASSWORD >=", value, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordLessThan(String value) {
            addCriterion("V_PASSWORD <", value, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordLessThanOrEqualTo(String value) {
            addCriterion("V_PASSWORD <=", value, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordLike(String value) {
            addCriterion("V_PASSWORD like", value, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordNotLike(String value) {
            addCriterion("V_PASSWORD not like", value, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordIn(List<String> values) {
            addCriterion("V_PASSWORD in", values, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordNotIn(List<String> values) {
            addCriterion("V_PASSWORD not in", values, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordBetween(String value1, String value2) {
            addCriterion("V_PASSWORD between", value1, value2, "vPassword");
            return (Criteria) this;
        }

        public Criteria andVPasswordNotBetween(String value1, String value2) {
            addCriterion("V_PASSWORD not between", value1, value2, "vPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordIsNull() {
            addCriterion("PAY_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPayPasswordIsNotNull() {
            addCriterion("PAY_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPayPasswordEqualTo(String value) {
            addCriterion("PAY_PASSWORD =", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordNotEqualTo(String value) {
            addCriterion("PAY_PASSWORD <>", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordGreaterThan(String value) {
            addCriterion("PAY_PASSWORD >", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_PASSWORD >=", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordLessThan(String value) {
            addCriterion("PAY_PASSWORD <", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordLessThanOrEqualTo(String value) {
            addCriterion("PAY_PASSWORD <=", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordLike(String value) {
            addCriterion("PAY_PASSWORD like", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordNotLike(String value) {
            addCriterion("PAY_PASSWORD not like", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordIn(List<String> values) {
            addCriterion("PAY_PASSWORD in", values, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordNotIn(List<String> values) {
            addCriterion("PAY_PASSWORD not in", values, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordBetween(String value1, String value2) {
            addCriterion("PAY_PASSWORD between", value1, value2, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordNotBetween(String value1, String value2) {
            addCriterion("PAY_PASSWORD not between", value1, value2, "payPassword");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VIP
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 01 08:54:57 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VIP
     *
     * @mbggenerated Thu Nov 01 08:54:57 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}